languages:
  PHP: true
engines:
  phpcodesniffer:
    enabled: true
    config:
      file_extensions: "php"
      standard: "WordPress"
ratings:
  paths:
  - classes/**
  - templates/**
  - "**.php"
exclude_paths:
  - docs/**/*
  - tests/**/*
