checks:
  php:
    avoid_closing_tag: false
    avoid_superglobals: false
    coding_standard:
      name: WordPress
    no_exit: false
    no_global_keyword: false
    one_class_per_file: false
    psr2_class_declaration: false
    psr2_control_structure_declaration: false
    psr2_switch_declaration: false
    variable_existence: false
    verify_access_scope_valid: false
    verify_argument_usable_as_reference: false
    verify_property_names: false
filter:
    excluded_paths:
        - 'bin/*'
        - 'docs/*'
        - '*.min.js'
        - '*.min.css'
        - 'assets/js/vendor/**/*.js'
        - 'assets/js/vendor/**/*.css'
        - 'node_modules/**/*'
        - tests/
        - vendor/
        - 'tests/**/*'
        - 'vendor/**/*'
        - 'Gulpfile.js'
        - 'wordpress/**/*.js'
        - 'wordpress/**/*.css'
    dependency_paths:
        - wordpress/
tools:
    php_code_sniffer:
        config:
            standard: WordPress
build:
    environment:
      node: 'v11.0.0'
      php: '7.1.25'
      mysql: true
      apache2:
        modules:
          - rewrite
    nodes:
        analysis:
            dependencies:
                before:
                    - composer require --dev johnpbloch/wordpress
