checks:
    php: true
    javascript: false
filter:
    excluded_paths:
        - 'bin/*'
        - 'docs/*'
        - '*.min.js'
        - '*.min.css'
        - tests/**/*
        - 'Gulpfile.js'
    dependency_paths:
        - wordpress/
tools:
    php_code_sniffer:
        config:
            standard: WordPress
